web/sitio/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from apps.inicio import views as vista
from apps.noticias.views import vista_noticia, vista_todas
from apps.suscribir import views as inscribir
from apps.multimedia import views as multimedia
from apps.encuesta import views as encuesta

urlpatterns = [
    url(r'^adminunivrso/', admin.site.urls),
    url(r'^api/', include('apps.api.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^404/$', vista.handler404, name='handler404'),
    url(r'^500/$', vista.handler500, name='handler500'),
    url(r'^noticia/(\d+)/$', vista_noticia, name = 'noticia'),
    url(r'^noticias/$', vista_todas, name = 'noticias'),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'^inscribir/', inscribir.inscripcion_congreso, name='inscribir'),
    url(r'^suscribir/', inscribir.suscribir_correos, name='suscribir'),
    # url(r'^congreso/', vista.vista_congreso, name='congreso'),
    url(r'^multimedia/', multimedia.vista_video, name='multimedia'),
    url(r'^encuesta/', encuesta.vista_encuesta, name='encuesta'),
    url(r'^$', vista.vista_inicio, name='index'),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web/apps/encuesta/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.db import models

# Modelo de la Encuesta para MOOC
class Encuesta(models.Model):
    email = models.EmailField(max_length=100, blank=False, null=False)
    informo = models.CharField(max_length=250, default='')
    mejoraria = models.CharField(max_length=200, default='')
    realizaria = models.CharField(max_length=250, default='')
    region = models.CharField(max_length=200, default='')
    comuna = models.CharField(max_length=200, default='')

web/apps/inicio/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

web/apps/multimedia/models.py
from django.db import models
from datetime import datetime
from django.core.files.images import get_image_dimensions
from django.core.exceptions import ValidationError


def validate_image(fieldfile_obj):
    filesize = fieldfile_obj.file.size
    w, h = get_image_dimensions(fieldfile_obj)
    megabyte_limit = 1.0
    if filesize > megabyte_limit*2*1024*1024:
        raise ValidationError("El tamano maximo permitido es de %sMB" % str(megabyte_limit))
    if w != 1280 or h != 720:
        raise ValidationError("Las dimensiones de la imagen son de %ix%i pixeles, y estas deben ser de 1280x720px" %(h,w))


# Create your models here.
class Video(models.Model):
    fecha_modificado = models.DateTimeField(auto_now = True)
    fecha_actual = models.DateTimeField(default=datetime.now())
    titulo = models.CharField(max_length=200)
    epigrafe = models.CharField(max_length=200)
    youtube_id = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to='multimedia/', height_field=None, width_field=None, max_length=200, validators=[validate_image], help_text='Tamano maximo de la imagen es de 2Mb y sus dimensiones deben ser de 1280x720px')
    descripcion = models.TextField(max_length=1500)
    activo = models.BooleanField(default=True)

    def __unicode__(self):
        return self.titulo

    class Meta:
        ordering = ["fecha_modificado"]
        verbose_name_plural = "Videos"

    def image_img(self):
        if self.imagen:
            return u'<img width="125px" height="auto" src="%s" />' % self.imagen.url
        else:
            return '(Sin imagen)'
    image_img.short_description = 'Imagen'
    image_img.allow_tags = True

web/apps/noticias/models.py
#!/usr/bin/python
# -*- coding: utf-8 -*-

from django.db import models
from datetime import datetime
from django.core.files.images import get_image_dimensions
from django.core.exceptions import ValidationError
from ckeditor.fields import RichTextField


def validate_image(fieldfile_obj):
    filesize = fieldfile_obj.file.size
    w, h = get_image_dimensions(fieldfile_obj)
    megabyte_limit = 2.0
    if filesize > megabyte_limit*2048*1024:
        raise ValidationError("El tamano maximo permitido es de %sMB" % str(megabyte_limit))
    if w != 1280 and h != 720:
        raise ValidationError("Las dimensiones de la imagen son de %ix%i pixeles, y estas deben ser de 1280x720px" %(h,w))


class Noticia(models.Model):
    titulo = models.CharField(max_length=200, blank=False, null=False)
    titulo_en = models.CharField(max_length=200, blank=False, null=False)
    cuerpo = RichTextField(max_length=10000, config_name='awesome_ckeditor')
    cuerpo_en = RichTextField(max_length=10000, config_name='awesome_ckeditor')
    imagen = models.ImageField(upload_to='noticias/', height_field=None, width_field=None, max_length=100, validators=[validate_image], help_text='Tamano maximo de la imagen es de 2Mb y sus dimensiones deben ser de 1280x720px')
    autor = models.CharField(max_length=200,blank=False, null=False)
    pie_imagen = models.CharField(max_length=300, blank=True, null=True)
    pie_imagen_en = models.CharField(max_length=300, blank=True, null=True)
    fecha_creacion = models.DateTimeField()

    class Meta:
        ordering = ['-fecha_creacion']
        verbose_name_plural = "noticias"

    def __unicode__(self):
        return self.titulo;

    def image_foto(self):
        if self.imagen:
            return u'<img width="125px" height="auto" src="%s" />' % self.imagen.url
        else:
            return '(Sin imagen)'
    image_foto.short_description = 'Imagen'
    image_foto.allow_tags = True

web/apps/encuesta/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django import forms
from .models import Encuesta

# Formulario utilizado en encuestas para los MOOC
class FormularioEncuesta(forms.Form):
    CHOICEINFORMO = [('redes', 'Redes Sociales'),
                 ('correo', 'Correo electrónico'),
                 ('charlas', 'Charlas de Astronomía'),
                 ('otro', 'Otro')]

    OECD = [ ('ninguno', ''),
             ('Matematicas', 'Matemáticas'),
             ('Ciencias de la Informacion y Computacion', 'Ciencias de la Información y Computación'),
             ('Ciencias Fisicas', 'Ciencias Físicas'),
             ('Ciencias Quimicas', 'Ciencias Químicas'),
             ('Ciencias de la Tierra y del Medio Ambiente', 'Ciencias de la Tierra y del Medio Ambiente'),
             ('Ciencias Biologicas', 'Ciencias Biológicas'),
             ('Ingenieria Civil', 'Ingeniería Civil'),
             ('Ingenieria Electrica, Ingenieria Electronica, Informatica', 'Ingeniería Eléctrica, Ingeniería Electrónica, Informática'),
             ('Ingenieria Mecanica', 'Ingeniería Mecánica'),
             ('Ingenieria Quimica', 'Ingeniería Química'),
             ('Ingenieria de los Materiales', 'Ingeniería de los Materiales'),
             ('Ingenieria Medica', 'Ingeniería Médica'),
             ('Ingenieria Ambiental', 'Ingeniería Ambiental'),
             ('Biotecnologia Ambiental', 'Biotecnología Ambiental'),
             ('Biotecnologia Industrial', 'Biotecnología Industrial'),
             ('Nanotecnologia', 'Nanotecnología'),
             ('Medicina Basica', 'Medicina Básica'),
             ('Medicina Clinica', 'Medicina Clínica'),
             ('Ciencias de la Salud', 'Ciencias de la Salud'),
             ('Biotecnologia Medica', 'Biotecnología Médica'),
             ('Agricultura, Silvicultura, Pesca', 'Agricultura, Silvicultura, Pesca'),
             ('Ciencia Animal y Lecheria', 'Ciencia Animal y Lechería'),
             ('Ciencias Veterinarias Biotecnologia Agricola', 'Ciencias Veterinarias Biotecnología Agrícola'),
             ('Psicologia', 'Psicología'),
             ('Economia y Negocios', 'Economía y Negocios'),
             ('Ciencias de la Educacion', 'Ciencias de la Educación'),
             ('Sociologia', 'Sociología'),
             ('Antropologia', 'Antropología'),
             ('Derecho', 'Derecho'),
             ('Ciencias Politicas', 'Ciencias Políticas'),
             ('Geografia Economica y Social', 'Geografía Económica y Social'),
             ('Comunicacion y Medios', 'Comunicación y Medios'),
             ('Historia y Arqueologia', 'Historia y Arqueología'),
             ('Lenguage y Literatura', 'Lenguage y Literatura'),
             ('Filosofia, Etica y Religion', 'Filosofía, Etica y Religión'),
             ('Arte', 'Arte (Artes, Historia del Arte, Artes Escénicas, Música)')
           ]

    email = forms.EmailField(max_length=254, label='Email (*)', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Ingrese su Email', 'pattern':'[A-Z0-9a-z]+([._%+-]*[A-Z0-9a-z]+)?@[A-Za-z0-9.-]+\\.[A-Za-z]{2,64}', 'required':''}))
    informo = forms.ChoiceField(label='¿A través de qué medios se informó del curso? (*)', choices=CHOICEINFORMO, initial='redes', widget=forms.RadioSelect(attrs={'class':'form-check'}))
    mejoraria = forms.CharField(max_length=200,label='¿Qué nos recomendaría para mejorar nuestro curso? (*)', widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Indique su recomendación'}))
    realizar = forms.ChoiceField(label='¿Qué MOOC le gustaría realizar con nosotros? (*)', choices=OECD,  initial='ninguno', widget=forms.Select(attrs={'class':'form-control','id': 'realizar'}))

web/apps/encuesta/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
from .models import Encuesta
from .forms import FormularioEncuesta
from django.http import HttpResponse
from django.views.decorators.clickjacking import xframe_options_exempt

# Visualización Encuesta para MOOC
#@xframe_options_exempt
def vista_encuesta(request):
    form_encuesta = FormularioEncuesta()
    if request.method == "POST":
        form_encuesta = FormularioEncuesta(request.POST)
        regiones = request.POST['regiones'].encode('utf8')
        comunas = request.POST['comunas'].encode('utf8')

        if form_encuesta.is_valid():
            informo = form_encuesta.cleaned_data.get('informo').encode('utf8')
            if informo == 'otro':
                informo = "otro: "+request.POST['otro_medio']

            nueva_encuesta = Encuesta.objects.create(
                email = form_encuesta.cleaned_data.get('email'),
                informo = informo,
                region = regiones,
                comuna = comunas,
                mejoraria = form_encuesta.cleaned_data.get('mejoraria'),
                realizaria = form_encuesta.cleaned_data.get('realizar')
            )
            nueva_encuesta.save()
            form_encuesta = FormularioEncuesta()
            return render(request, 'encuesta.html', {'form_encuesta': form_encuesta, 'procesado':'procesado'})
        else:
            return render(request, 'encuesta.html', {'form_encuesta': form_encuesta})
            # print("Email: "+form_encuesta.cleaned_data.get('email').encode('utf8'))
            # print("informo: "+form_encuesta.cleaned_data.get('informo').encode('utf8'))
            # print("mejoraria: "+form_encuesta.cleaned_data.get('mejoraria').encode('utf8'))
            # print("realizar: "+form_encuesta.cleaned_data.get('realizar').encode('utf8'))
    else:
        return render(request, 'encuesta.html', {'form_encuesta': form_encuesta})

web/apps/inicio/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from ..noticias.models import Noticia
from ..equipo.models import Equipo, Categorias
from ..suscribir.models import Suscribir, Congreso
from ..suscribir.forms import FormularioSuscribir, FormularioCongreso
from ..moocs.models import Mooc


# Create your views here.
def vista_inicio(request):
    noticias = Noticia.objects.all()[:5]
    categorias = Categorias.objects.all().order_by('prioridad')
    equipos = Equipo.objects.all()
    cientificos = Equipo.objects.filter(categoria__nombre='cientifico').order_by('prioridad')
    administrativos = Equipo.objects.filter(categoria__nombre= 'administrativo').order_by('prioridad')
    tecnicos = Equipo.objects.filter(categoria__nombre= 'tecnico').order_by('prioridad')
    audiovisuales = Equipo.objects.filter(categoria__nombre= 'audiovisual').order_by('prioridad')
    moocs = Mooc.objects.filter(visible=True).order_by('prioridad')

    # Lectura variables de formulario
    form_congreso = FormularioCongreso()
    formulario = FormularioSuscribir()

    return render(request, 'inicio.html', {'form_congreso': form_congreso,'formulario': formulario, 'noticias': noticias, 'categorias': categorias, 'equipos': equipos, 'cientificos': cientificos , 'administrativos': administrativos , 'tecnicos': tecnicos, 'audiovisuales': audiovisuales, 'moocs': moocs})


def vista_desarrollo(request):
    return render(request, 'endesarrollo.html',)

def vista_congreso(request):
    return render(request, 'congreso.html',)

def handler404(request):
    return render(request, '404.html', status=404)

def handler500(request):
    return render(request, '500.html', status=500)

web/apps/multimedia/views.py
from django.shortcuts import render
from .models import Video

# Create your views here.
def vista_video(request):
    videos = Video.objects.all()
    return render(request, 'multimedia.html', {'videos' :videos})

web/apps/noticias/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render, redirect
from .models import Noticia

# Vista Noticia
def vista_noticia(request, noticia_id):
    ultimas = Noticia.objects.all().order_by('-id')
    n = Noticia.objects.filter(id=noticia_id)
    if n.exists():
        return render(request, 'noticias.html', {'noticia': n, 'ultimas': ultimas})
    return redirect('apps.inicio.views.vista_inicio')


def vista_todas(request):
    noticias = Noticia.objects.all().order_by('-id')
    return render(request, 'todaslasnoticias.html', {'noticias': noticias})

web/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Campus Digital">
        <meta name="keywords" content="userena, campus digital, uls, la serena, aprendizaje, online, vr, realidad virtual, astroturismo, turismo, cielo, region estrella, observatorio">
        <!--Title-->
        <title>{% block title %}unIVrso{% endblock %}</title>
        <!--Google Fonts-->
        <link href="https://fonts.googleapis.com/css?family=Nunito:400,300,500,700,800,100,60" rel="stylesheet" type="text/css">
        <link rel="shortcut icon" href="{% static 'images/iconos/favicon.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/iconos/apple-touch-icon-144-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/iconos/apple-touch-icon-114-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/iconos/apple-touch-icon-72-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" href="{% static 'images/iconos/apple-touch-icon-57-precomposed.png' %}">
        <!--CSS-->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/animate.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/astro-animation.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/custom.css' %}?v=2" rel="stylesheet" type="text/css" >
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-69096629-6"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-69096629-6');
        </script>
    </head>
    <body>
        <div class="body-navegation">
            {% block navegation %}{% include 'navegacion.html' %}{% endblock %}
        </div>
        <div class="body-content">
            {% block content %}{% endblock %}
        </div>
        <div class="body-footer">
            {% block footer %}{% include 'footer.html' %}{% endblock %}
        </div>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="http://maps.google.com/maps/api/js?key=AIzaSyCzXBBNKv9wLH9Avm_SLdScfLX0F8m0HPs&sensor=true"></script>
        <script type="text/javascript" src="{% static 'js/gmaps.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.inview.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.countTo.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.parallax.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/mousescroll.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.mixitup.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/canvas.js' %}"></script>
        <!--script type="text/javascript" src="{% static 'js/pre_loader.js' %}"></script -->
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/custom.js' %}?v=2"></script>
        {% block javascript %}{% endblock %}
    </body>
</html>

web/templates/base_encuesta.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="Campus Digital">
        <meta name="keywords" content="userena, campus digital, uls, la serena, aprendizaje, online, vr, realidad virtual, astroturismo, turismo, cielo, region estrella, observatorio">
        <!--Title-->
        <title>{% block title %}unIVrso{% endblock %}</title>
        <!--Google Fonts-->
        <link href="https://fonts.googleapis.com/css?family=Nunito:400,300,500,700,800,100,60" rel="stylesheet" type="text/css">
        <link rel="shortcut icon" href="{% static 'images/iconos/favicon.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="144x144" href="{% static 'images/iconos/apple-touch-icon-144-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="114x114" href="{% static 'images/iconos/apple-touch-icon-114-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" sizes="72x72" href="{% static 'images/iconos/apple-touch-icon-72-precomposed.png' %}">
        <link rel="apple-touch-icon-precomposed" href="{% static 'images/iconos/apple-touch-icon-57-precomposed.png' %}">
        <!--CSS-->
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/prettyPhoto.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/animate.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/astro-animation.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/responsive.css' %}" rel="stylesheet" type="text/css" >
        <link href="{% static 'css/custom.css' %}?v=2" rel="stylesheet" type="text/css" >
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-69096629-6"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'UA-69096629-6');
        </script>
    </head>
    <body>
        <div class="body-navegation">
            {% block navegation %}{% include 'navegacion.html' %}{% endblock %}
        </div>
        <div class="body-content">
            {% block content %}{% endblock %}
        </div>
        <div class="body-footer">
            {% block footer %}{% include 'footer.html' %}{% endblock %}
        </div>
        <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
        <script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.inview.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.countTo.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.parallax.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/mousescroll.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.prettyPhoto.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/jquery.mixitup.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/canvas.js' %}"></script>
        <!--script type="text/javascript" src="{% static 'js/pre_loader.js' %}"></script -->
        <script type="text/javascript" src="{% static 'js/custom.js' %}?v=2"></script>
        {% block javascript %}{% endblock %}
    </body>
</html>

web/templates/congreso.html
{% extends "base.html" %}
{% load staticfiles %}
{% load i18n %}
{% block title %}uniVRso | Campus Digital{% endblock %}

{% block content %}

<!--/# Slider Area-->
<div id="congreso">

    <!-- Start About Us -->
    <div class="container-full padding-top" style="padding-top:71px !important">
        <div class="row section-title text-center" style="padding-bottom:50px">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"
                <p>
                  <img src="{% static 'images/congreso/banner-congreso.jpg' %}" alt="Banner" width="100%" />
                  <div style="text-align:center">
                    <img src="{% static 'images/congreso/programa-congreso.jpg' %}" alt="Programa" width="80%"/>
                  </div>
                </p>
            </div>
        </div>

      </div>
</div>

{% endblock %}

web/templates/encuesta.html
{% extends "base_encuesta.html" %}
{% load staticfiles %}
{% load i18n %}
{% block title %}uniVRso | Campus Digital{% endblock %}
{% block navegation %}{% endblock %}
{% block content %}


<div id="inicio">
  <div class="row section-title padding-top" style="padding-bottom: 50px !important;padding-top: 50px !important">
      <div class="col-12">
        <center><h2>Danos tu Opinión</h2></center>
        <!-- <center><h3>Curso de Astronomía general, aplicada a los cielos de la Región de Coquimbo</h3></center> -->
      </div>
  </div>

  <div class="container" style="padding-bottom:50px">
    {% if procesado %}
      <div class="alert alert-success"><br>Hemos recibido su cuestionario. Ahora puede continuar con la Secuencia de Aprendizaje. Muchas Gracias !!!<br><br></div>
    {% endif %}
    <div class="col-12" style="text-align:justify">
      Estimados y Estimadas,<br><br>
      Hemos llegado al final del MOOC 2 <b>¿Qué tipo de Ciencia se desarrolla en los observatorios de la Región de Coquimbo?</b>. Ahora resta contestar este breve formulario que a su vez es un <b>requisito para la obtención de tu constancia de participación</b>, para ello dispondrás hasta el día Viernes 8 de Noviembre a las 23:59 hrs. Muchas gracias por tu participación.
    </div>
    <br><br>
    <form id="form_encuesta" name="form_encuesta" action="#" method="POST" accept-charset="UTF-8">
      {% csrf_token %}
      <div class="form-group">
        <label for="email">{{ form_encuesta.email.label }}</label>
        {{ form_encuesta.email }}
      </div>
      <div class="col-lg-12 col-md-12 col-sm-12">
        {% for error_email in form_encuesta.email.errors %}
          <div class="alert alert-danger" role="alert">{{ error_email }}</div>
        {% endfor %}
      </div>

      <div class="form-group">
        <label for="id_informo">{{ form_encuesta.informo.label }}</label>
        {{ form_encuesta.informo }}
        <input id="otro_medio" name="otro_medio" class="form-control" type="text" placeholder="Indicar otro medio por el cual se informó" readonly>
      </div>

      <div class="form-group">
        <label for="regiones">¿De qué Región es usted?</label><br/>
        <select id="regiones" name="regiones" class="form-control"></select>
      </div>
      <div class="form-group">
        <label for="comunas">¿De qué comuna es usted?</label><br/>
        <select id="comunas" name="comunas" class="form-control"></select>
      </div>
      <div class="form-group">
        <label for="mejoraria">{{ form_encuesta.mejoraria.label }}</label>
        {{ form_encuesta.mejoraria }}
      </div>
      <div class="form-group">
        <label for="realizar">{{ form_encuesta.realizar.label }}</label><br>
        {{ form_encuesta.realizar }}
      </div>
      <button id="enviar_encuesta" type="submit" class="btn btn-primary">Enviar</button>
    </form>
  </div>
</div>

{% endblock %}

web/templates/endesarrollo.html
{% extends "base.html" %}
{% load staticfiles %}
{% block title %}Sitio en desarrollo{% endblock %}

{% block content %}
    <div class="row">
      <div class="col-md-12" style="margin-top: 100px;">
          <center>
              <img src="{% static 'images/iconos/oops.png' %}" alt="" />
          </center>
      </div>
      <div class="col-md-12" style="margin-bottom: 50px;">
          <center>
            <div class="titulo" style="font-size:4em;padding:0px;color:#009fe3;text-align:center;">
                <p>Sitio en construcción</p>
            </div>
          </center>
      </div>
      <div class="col-md-12">
          <center>
              <img src="{% static 'images/iconos/campusito_huevo.png' %}" alt="" />
          </center>
      </div>
    </div>
{% endblock %}